# Generated by Django 2.2.6 on 2019-10-31 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191031_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='breeding',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='enclosure',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='feeding',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='female',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='animal',
            name='incubation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='male',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='animal',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='reptiletype',
            field=models.CharField(blank=True, choices=[('X', 'choose type of reptile: crocodile, lizard, snake, turtle'), ('C', 'Crocodile'), ('L', 'Lizard'), ('S', 'Snake'), ('T', 'Turtle')], default='X', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='sex',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='animal',
            name='cites',
            field=models.CharField(blank=True, choices=[('X', 'Cites of animal'), ('A', 'Cites A or I'), ('B', 'Cites B or II'), ('C', 'Cites C or III'), ('D', 'Cites D or none')], default='X', max_length=1, null=True),
        ),
    ]
