# Generated by Django 2.2.6 on 2019-10-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191031_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='temperature',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
