# Generated by Django 2.2.6 on 2019-11-01 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_animal_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('animalpictures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.Animal')),
            ],
        ),
    ]
