# Generated by Django 2.2.6 on 2019-11-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_animalimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='views',
        ),
        migrations.AlterField(
            model_name='animal',
            name='reptiletype',
            field=models.CharField(blank=True, choices=[('X', 'Choose type of reptile'), ('C', 'Crocodile'), ('L', 'Lizard'), ('S', 'Snake'), ('T', 'Turtle')], default='X', max_length=1, null=True),
        ),
    ]
